### ISSUE TITLE
Getting  an error with socket_create()

### ISSUE THREAD

**Issue by Mulkave** [qualtrics/jaeger-client-php#1]
```
Uncaught Error: Call to undefined function Jaeger\Transport\socket_create() in .../src/Jaeger/Transport/TUDPTransport.php:25
```

**Comment by tylerchr** [comment]
More information about your situation is necessary for me to address your report. What version of PHP are you using, and do you have any special `php.ini` options that may affect the way namespaces resolve? Have you found any workarounds that fix this error that may help shed light on its cause?

According to the PHP documentation, unqualified function names will ultimately resolve to the global namespace. That should be (and, at least for most users, _is_) happening here.

> For functions and constants, PHP will fall back to global functions or constants if a namespaced function or constant does not exist.
>
> http://php.net/manual/en/language.namespaces.fallback.php

Perhaps you somehow have a PHP build that is missing the `socket_create` function, so it errors after failing to find it in `namespace Jaeger\Transport`?

**Comment by Mulkave** [comment]
1. PHP version:
```
PHP 7.1.22 (cli) (built: Sep 13 2018 21:14:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.22, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```
2. Nothing special in my `php.ini`, built-in functions work as expected as far as i've used, never used `socket_create()` though
3. Couldn't resolve the issue yet, no

**Q**: Is `socket_create` provided in an extension? or something that needs to be added to have this provided?
